---
# Targets instances tagged `ubuntu-base`

- name: Bootstrap Ubuntu
  import_playbook: bootstrap-ubuntu.yml

- hosts: ubuntu-base

  become: yes
  become_user: root

  roles:
    - { role: 'vermilion_tech.ansible_role_ubuntu_base', tags: 'ubuntu-base' }
